version: '3.8'

services:
  ssh:
    image: mozzi20/ssh-spawner
    volumes:
      - ./id_rsa:/id_rsa
      - ./config.yaml:/config.yaml
      - //var/run/docker.sock:/var/run/docker.sock
    ports:
      - "22:22"
