// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package main

import (
	"github.com/movitz-s/ssh-spawner/shells"
)

// Injectors from wire.go:

func initializeShellService() (shells.ShellService, error) {
	client, err := newDockerClient()
	if err != nil {
		return nil, err
	}
	shellService := shells.NewDockerShellService(client)
	return shellService, nil
}
