// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package main

import (
	"github.com/movitz-s/ssh-spawner/server"
	"github.com/movitz-s/ssh-spawner/shells"
)

// Injectors from wire.go:

func initializeShellService() (shells.ShellService, error) {
	client, err := newDockerClient()
	if err != nil {
		return nil, err
	}
	shellService := shells.NewDockerShellService(client)
	return shellService, nil
}

func initializeSSHServer() (*server.Server, error) {
	signer, err := loadPrivateKey()
	if err != nil {
		return nil, err
	}
	serverConfig := newSSHConfig(signer)
	shellService, err := initializeShellService()
	if err != nil {
		return nil, err
	}
	config := newConfig()
	serverServer := server.NewServer(serverConfig, shellService, config)
	return serverServer, nil
}
