// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package main

import (
	"github.com/movitz-s/ssh-spawner/shells"
)

// Injectors from wire.go:

func InitializeShellService() shells.ShellService {
	client := NewDockerClient()
	shellService := shells.NewDockerShellService(client)
	return shellService
}
