// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package spawner

import (
	"github.com/movitz-s/ssh-spawner/internal/spawner/server"
	"github.com/movitz-s/ssh-spawner/internal/spawner/shells"
)

// Injectors from wire.go:

func initializeShellService() (shells.ShellService, func(), error) {
	client, cleanup, err := newDockerClient()
	if err != nil {
		return nil, nil, err
	}
	shellService := shells.NewDockerShellService(client)
	return shellService, func() {
		cleanup()
	}, nil
}

func InitializeSSHServer() (*server.Server, func(), error) {
	signer, err := loadPrivateKey()
	if err != nil {
		return nil, nil, err
	}
	serverConfig := newSSHConfig(signer)
	shellService, cleanup, err := initializeShellService()
	if err != nil {
		return nil, nil, err
	}
	config := newConfig()
	serverServer := server.NewServer(serverConfig, shellService, config)
	return serverServer, func() {
		cleanup()
	}, nil
}
